### ISSUE TITLE
Qnet crashes on certain sequence lengths

### ISSUE THREAD

**Issue by RuolinZheng08** [zeroknowledgediscovery/quasinet#15]
Add the following code to `qnet_construction.ipynb` and run the entire notebook

```python
qnet.membership_degree(np.empty(504, dtype=str), infbiome_qnet) # crashes
qnet.membership_degree(np.empty(505, dtype=str), infbiome_qnet) # ok, outputs 0.0
```

**Comment by JinLi711** [comment]
The length of the input sequence should match the size of the `feature_names` that was passed to the construction of the qnet.

I added some input size checking to fix this problem. 

41c9dc14ba6b6abacc021bce0e18b7c79f6bb14d
